<?php

namespace StoreBundle\Repository\Store\Excursion;

/**
 * TeaserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeaserRepository extends \Doctrine\ORM\EntityRepository
{
}
