services:
  aw.synchronization.datasource_manager:
    class: Accurateweb\SynchronizationBundle\Model\Datasource\DatasourceManager

  aw.synchronization.datasource.ftp:
    class: Accurateweb\SynchronizationBundle\Model\Datasource\FTPDataSource
    arguments:
      - { host: speedtest.tele2.net, username: anonymous, password: user@example.com }
    tags:
      - { name: 'aw.datasource' }

  aw.synchronization.datasource.moy_sklad.products.folders:
    class: StoreBundle\Synchronization\FromMoySklad\Model\Datasource\CatalogDataSource
    arguments:
      - {}
      - ~
      - "@doctrine.orm.default_entity_manager"
      - '%moysklad_username%'
      - '%moysklad_password%'
      - '%kernel.root_dir%'
      - '@event_dispatcher'
      - '@accurateweb.slugifier.yandex'
      - '@logger'
    tags:
      - { name: 'aw.datasource' }

  aw.synchronization.datasource.moy_sklad.warehouse:
    class: StoreBundle\Synchronization\FromMoySklad\Model\Datasource\WarehouseDatasource
    arguments:
      - {}
      - ~
      - "@doctrine.orm.default_entity_manager"
      - '%moysklad_username%'
      - '%moysklad_password%'
      - '%kernel.root_dir%'
      - '@event_dispatcher'
      - '@accurateweb.slugifier.yandex'
      - '@logger'
    tags:
      - { name: 'aw.datasource' }

  aw.synchronization.datasource.moy_sklad:
    class: StoreBundle\Synchronization\FromMoySklad\Model\Datasource\MoySkladSource
    arguments:
      - {}
      - ~
      - "@doctrine.orm.default_entity_manager"
      - '%moysklad_username%'
      - '%moysklad_password%'
      - '%kernel.root_dir%'
      - '@event_dispatcher'
      - '@accurateweb.slugifier.yandex'
      - '@logger'
    tags:
      - { name: 'aw.datasource' }

  aw.synchronization.datasource.moy_sklad.products.image:
    class: StoreBundle\Synchronization\FromMoySklad\Model\Datasource\MoySkladProductImageDataSource
    arguments:
      - {}
      - ~
      - "@doctrine.orm.default_entity_manager"
      - '%moysklad_username%'
      - '%moysklad_password%'
      - '%kernel.root_dir%'
      - '@event_dispatcher'
    tags:
      - { name: 'aw.datasource' }