services:
  aw.synchronization.parser.json_parser:
      class: StoreBundle\Synchronization\Parser\JsonParser
      arguments:
        - ~
        - ~
        - '@aw.synchronization.entity_factory.moy_sklad'
        - '@aw.synchronization.schema.common'
        - {}
      tags:
        - { name: 'aw.parser' }

  aw.synchronization.parser.json_parser.product_images:
      class: StoreBundle\Synchronization\Parser\JsonParser
      arguments:
        - ~
        - ~
        - '@aw.synchronization.entity_factory.moy_sklad'
        - '@aw.synchronization.schema.moy_sklad.product_images'
        - {}
      tags:
        - { name: 'aw.parser' }

  aw.synchronization.parser.json_parser.product_folders:
      class: StoreBundle\Synchronization\Parser\JsonParser
      arguments:
        - ~
        - ~
        - '@aw.synchronization.entity_factory.moy_sklad'
        - '@aw.synchronization.schema.moy_sklad.product_folders'
        - {}
      tags:
        - { name: 'aw.parser' }