services:
  aw.synchronization.scenario_manager:
    class: Accurateweb\SynchronizationBundle\Model\Scenario\ScenarioManager
  # moy_sklad_product_photo: '@aw.synchronization.subject.moy_sklad.products.images', moy_sklad_bundles_photo: '@aw.synchronization.subject.moy_sklad.bundles.images',
  aw.synchronization.sync.moy_sklad:
    class:  Accurateweb\SynchronizationBundle\Model\Scenario\MoySkladScenario
    arguments:
      - "@event_dispatcher"
      - 'moy_sklad'
      - { moy_sklad_folder: '@aw.synchronization.subject.moy_sklad.products_folders', moy_sklad: '@aw.synchronization.subject.moy_sklad.products', moy_sklad_bundles: '@aw.synchronization.subject.moy_sklad.bundles', moy_sklad_warehouse: '@aw.synchronization.subject.moy_sklad.warehouses'}
      - "@doctrine.orm.default_entity_manager"
      - "@logger"
      - '%kernel.root_dir%'
    tags:
      - { name: 'aw.synchronization.scenario' }