services:
  aw.synchronization.schema_manager:
    class: Accurateweb\SynchronizationBundle\Model\Schema\SynchronizationSchemaManager

  aw.synchronization.schema.common:
    class: Accurateweb\SynchronizationBundle\Model\Schema\CommonSchema
    arguments:
      - { tableName: products, columns: {
                                          external_code: { type: VARCHAR, size: 255 },
                                          name: { type: VARCHAR, size: 1000},
                                          price: { type: DECIMAL, size: 10},
                                          sku: { type: VARCHAR, size: 1000, mapped_with: sku },
                                          slug: { type: VARCHAR, size: 1000 },
                                          description: { type: longtext },
                                          short_description: { type: VARCHAR, size: 1000 },
                                          is_with_gift: { type: tinyint },
                                          is_publication_allowed: { type: tinyint },
                                          published: { type: tinyint },
                                          created_at: { type: VARCHAR, size: 512 },
                                          total_stock: { type: int },
                                          reserved_stock: { type: int },
                                          is_free_delivery: { type: tinyint },
                                          rank: { type: DOUBLE }
                                          }}

                                           #weight` double DEFAULT NULL,1
                                           #length` double DEFAULT NULL,
                                           #width` double DEFAULT NULL,
                                           #height` double DEFAULT NULL,
                                           #volume` double DEFAULT NULL,