services:
  aw.synchronization.schema_manager:
    class: Accurateweb\SynchronizationBundle\Model\Schema\SynchronizationSchemaManager

  aw.synchronization.schema.moy_sklad.product_folders:
    class: Accurateweb\SynchronizationBundle\Model\Schema\CommonSchema
    arguments:
      - { tableName: moy_sklad_catalog, columns: {
                                         guid: { type: VARCHAR, size: 36 },
                                         parent_guid: { type: VARCHAR, size: 36 },
                                         name: { type: VARCHAR, size: 255 }
                                        }}

  aw.synchronization.schema.moy_sklad.warehouses:
    class: Accurateweb\SynchronizationBundle\Model\Schema\CommonSchema
    arguments:
      - { tableName: moy_sklad_warehouse, columns: {
                                         name: { type: VARCHAR, size: 36 },
                                         external_id: { type: VARCHAR, size: 255 },
                                         description: { type: TEXT },
                                         code: { type: VARCHAR, size: 36 },
                                         archived: { type: tinyint } ,
                                         parent: { type: VARCHAR, size: 36 },
                                         path_name: { type: VARCHAR, size: 36 }
                                        }}

  aw.synchronization.schema.common:
    class: Accurateweb\SynchronizationBundle\Model\Schema\CommonSchema
    arguments:
      - { tableName: products, columns: {
                                          external_code: { type: VARCHAR, size: 255 },
                                          name: { type: VARCHAR, size: 1000},
                                          moy_sklad_name: { type: VARCHAR, size: 1000},
                                          price: { type: DECIMAL, size: 10},
                                          wholesale_price: { type: DECIMAL, size: 10},
                                          purchase_price: { type: DECIMAL, size: 10},
                                          sku: { type: VARCHAR, size: 1000, mapped_with: sku },
                                          slug: { type: VARCHAR, size: 1000 },
                                          description: { type: longtext },
                                          short_description: { type: VARCHAR, size: 1000 },
                                          is_with_gift: { type: tinyint },
                                          is_publication_allowed: { type: tinyint },
                                          published: { type: tinyint },
                                          created_at: { type: VARCHAR, size: 512 },
                                          total_stock: { type: int },
                                          reserved_stock: { type: int },
                                          is_free_delivery: { type: tinyint },
                                          rank: { type: DOUBLE },
                                          bundle: { type: tinyint },
                                          package: {type: DECIMAL, size: 10 },
                                          unit_weight: {type: DECIMAL, size: 10 }
                                          }}

  aw.synchronization.schema.bundles:
    class: Accurateweb\SynchronizationBundle\Model\Schema\CommonSchema
    arguments:
      - { tableName: products, columns: {
                                          external_code: { type: VARCHAR, size: 255 },
                                          name: { type: VARCHAR, size: 1000},
                                          moy_sklad_name: { type: VARCHAR, size: 1000},
                                          price: { type: DECIMAL, size: 10},
                                          wholesale_price: { type: DECIMAL, size: 10},
                                          purchase_price: { type: DECIMAL, size: 10},
                                          sku: { type: VARCHAR, size: 1000, mapped_with: sku },
                                          slug: { type: VARCHAR, size: 1000 },
                                          description: { type: longtext },
                                          short_description: { type: VARCHAR, size: 1000 },
                                          is_with_gift: { type: tinyint },
                                          is_publication_allowed: { type: tinyint },
                                          published: { type: tinyint },
                                          created_at: { type: VARCHAR, size: 512 },
                                          total_stock: { type: int },
                                          reserved_stock: { type: int },
                                          is_free_delivery: { type: tinyint },
                                          rank: { type: DOUBLE },
                                          bundle: { type: tinyint },
                                          package: {type: DECIMAL, size: 10 },
                                          unit_weight: {type: DECIMAL, size: 10 }
                                          }}

  aw.synchronization.schema.moy_sklad.product_images:
    class: Accurateweb\SynchronizationBundle\Model\Schema\CommonSchema
    arguments:
      - { tableName: product_images, columns: {
                                          product_id: { type: INT, size: 11 },
                                          filename: { type: VARCHAR, size: 1000},
                                          position: { type: INT, size: 10 }
                                          }}