services:
  aw.synchronization.configuration_manager:
    class: Accurateweb\SynchronizationBundle\Model\Configuration\SynchronizationConfigurationManager

  aw.synchronization.configuration.moy_sklad:
    class: Accurateweb\SynchronizationBundle\Model\Configuration\SynchronizationServiceConfiguration
    arguments:
      - '@event_dispatcher'
      - '@doctrine.dbal.default_connection'
   #   - '@aw.synchronization.sync.moy_sklad'
      - '@aw.synchronization.subject.moy_sklad'
      - '@aw.synchronization.datasource.moy_sklad'
      - '%kernel.root_dir%'
      - 'moy_sklad'
    tags:
      - { name: 'aw.synchronization.config' }