services:
    app.admin.cheese_story:
      class: StoreBundle\Admin\Text\CheeseStoryAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: text
          label: Сырные заметки
      arguments:
        - null
        - StoreBundle\Entity\Text\CheeseStory
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.partner:
      class: StoreBundle\Admin\Text\PartnerAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: text
          label: Партнёры
      arguments:
        - null
        - StoreBundle\Entity\Text\Partner
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.promo_banner:
      class: StoreBundle\Admin\Text\PromoBannerAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: homepage
          label: Промо-баннеры
      arguments:
        - null
        - StoreBundle\Entity\Text\PromoBanner
        - 'PixSortableBehaviorBundle:SortableAdmin'
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.ship:
      class: StoreBundle\Admin\Store\Shipping\ShippingAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: store
          label: Доставка
      arguments:
        - null
        -  StoreBundle\Entity\Store\Shipping\ShippingMethod
        - 'PixSortableBehaviorBundle:SortableAdmin'