services:
    app.admin.cheese_story:
      class: StoreBundle\Admin\Text\CheeseStoryAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: main_page
          label: Сырные заметки
      arguments:
        - null
        - StoreBundle\Entity\Text\CheeseStory
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.partner:
      class: StoreBundle\Admin\Text\PartnerAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: main_page
          label: Партнёры
      arguments:
        - null
        - StoreBundle\Entity\Text\Partner
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.ship:
      class: StoreBundle\Admin\Store\Shipping\ShippingAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: store
          label: Способы доставки
      arguments:
        - null
        -  StoreBundle\Entity\Store\Shipping\ShippingMethod
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.pickup:
      class: StoreBundle\Admin\Store\Shipping\PickupPointAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: store
          label: Пункты самовывоза
      arguments:
        - null
        -  StoreBundle\Entity\Store\Shipping\PickupPoint
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.home_banner.admin:
      class: StoreBundle\Admin\HomeBannerAdmin
      arguments: [~, StoreBundle\Entity\Common\HomeBanner, 'PixSortableBehaviorBundle:SortableAdmin']
      tags:
        - {name: sonata.admin, manager_type: orm, group: main_page, label: "Тизерные блоки"}