services:
    app.admin.cheese_story:
      class: AppBundle\Admin\Text\CheeseStoryAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: text
          label: Сырные заметки
      arguments:
        - null
        - AppBundle\Entity\Text\CheeseStory
        - 'PixSortableBehaviorBundle:SortableAdmin'