services:
    app.admin.cheese_story:
      class: StoreBundle\Admin\Text\CheeseStoryAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: text
          label: Сырные заметки
      arguments:
        - null
        - StoreBundle\Entity\Text\CheeseStory
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.partner:
      class: StoreBundle\Admin\Text\PartnerAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: homepage
          label: Партнёры
      arguments:
        - null
        - StoreBundle\Entity\Text\Partner
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.promo_banner:
      class: StoreBundle\Admin\Text\PromoBannerAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: homepage
          label: Промо-баннеры
      arguments:
        - null
        - StoreBundle\Entity\Text\PromoBanner
        - 'PixSortableBehaviorBundle:SortableAdmin'
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.ship:
      class: StoreBundle\Admin\Store\Shipping\ShippingAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: store
          label: Способы доставки
      arguments:
        - null
        -  StoreBundle\Entity\Store\Shipping\ShippingMethod
        - 'PixSortableBehaviorBundle:SortableAdmin'

    app.admin.pickup:
      class: StoreBundle\Admin\Store\Shipping\PickupPointAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: store
          label: Пункты самовывоза
      arguments:
        - null
        -  StoreBundle\Entity\Store\Shipping\PickupPoint
        - 'PixSortableBehaviorBundle:SortableAdmin'


    app.admin.user_qustion:
      class: StoreBundle\Admin\Text\QuestionAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: questions
          label: Вопросы пользователей
      arguments:
        - null
        - StoreBundle\Entity\Text\Question
        - StoreBundle:Admin\Text\QuestionAdmin

    app.home_banner.admin:
      class: StoreBundle\Admin\HomeBannerAdmin
      arguments: [~, StoreBundle\Entity\Common\HomeBanner, 'PixSortableBehaviorBundle:SortableAdmin']
      tags:
        - {name: sonata.admin, manager_type: orm, group: homepage, label: "Тизерные блоки"}

    app.admin.contact_phone:
      class: StoreBundle\Admin\Text\ContactPhoneAdmin
      tags:
        -
          name: sonata.admin
          manager_type: orm
          group: settings
          label: Контактные телефоны
      arguments:
        - null
        - StoreBundle\Entity\Text\ContactPhone
        - ~

    aw_email_template_admin.email_template:
      class: StoreBundle\Admin\Store\Notification\EmailTemplateAdmin
      tags:
          -
            name: sonata.admin
            manager_type: orm
            group: %aw_email_template_admin.email_template_group%
            label: %aw_email_template_admin.email_template_label%
            label_catalogue: PropelEmailTemplateAdminBundle
      arguments:
          - null
          - %aw_email_template_admin.class%
          - SonataAdminBundle:CRUD
      calls:
          - [setModelManager, ['@aw_email_template_admin.model_manager'] ]
          - [setTemplate, [edit, AccuratewebEmailTemplateBundle:EmailTemplateAdmin:edit.html.twig]]