services:
    store.setting.abandoned_cart:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      public: false
      autowire: false
      arguments:
       - '@aw.settings.storage'
       - abandoned_cart_age
       - Возраст корзины в днях, при котором она считается брошенной.
       - 30
      tags:
        - { name: aw.setting }

    store.setting.default_order_status:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
       - '@aw.settings.storage'
       - '@store.order_status.repository'
       - default_order_status
       - Статус по умолчанию для нового заказа.
      tags:
        - { name: aw.setting }

    store.setting.default_order_payment_status:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
       - '@aw.settings.storage'
       - '@store.order_payment_status.repository'
       - default_order_payment_status
       - Статус оплаты по умолчанию для нового заказа.
      tags:
        - { name: aw.setting }

    store.setting.facebook_link:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'facebook_link'
        - 'Ссылка Facebook'
        - ~
      tags:
        - { name: aw.setting }

    store.setting.vk_link:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'vk_link'
        - 'Ссылка Вконтакте'
        - ~
      tags:
        - { name: aw.setting }

    store.setting.instagram_link:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'instagram_link'
        - 'Ссылка Instagram'
        - ~
      tags:
        - { name: aw.setting }

    store.setting.root_catalog_redirect:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'root_catalog_redirect'
        - 'Алиас, на который будет производиться редирект при попытке зайти в корневой радел каталога'
        - 'syr'
      tags:
        - { name: aw.setting }

    store.setting.cheese_hardness_property:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
        - '@aw.settings.storage'
        - '@store.product.attribute.repository'
        - 'cheese_hardness_property'
        - 'Свойство твердости для фильтра по сырам'
      tags:
        - { name: aw.setting }


    store.setting.cheese_mold_property:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
        - '@aw.settings.storage'
        - '@store.product.attribute.repository'
        - 'cheese_mold_property'
        - 'Свойство вида плесени для фильтра по сырам'
      tags:
        - { name: aw.setting }

    store.setting.warehouse_rezh:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      public: false
      autowire: false
      arguments:
       - '@aw.settings.storage'
       - warehouse_rezh
       - "Id склада, к которому будут привязываться заказы для города Реж"
       - '2ade3f32-889b-11e7-7a6c-d2a900028be0'
      tags:
        - { name: aw.setting }

    store.setting.warehouse_ekb:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      public: false
      autowire: false
      arguments:
       - '@aw.settings.storage'
       - warehouse_ekb
       - "Id склада, к которому будут привязываться заказы для города Екатеринбург"
       - '88a8756a-889c-11e7-7a69-8f5500016d1c'
      tags:
        - { name: aw.setting }

    store.setting.warehouse_other_city:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      public: false
      autowire: false
      arguments:
       - '@aw.settings.storage'
       - warehouse_other_city
       - "Id склада, к которому будут привязываться заказы для города получения «Другой город»"
       - '88a8756a-889c-11e7-7a69-8f5500016d1c'
      tags:
        - { name: aw.setting }

    #store.setting.synchronization.moy_sklad.products.folder:
    #  class: Accurateweb\SettingBundle\Model\Setting\JsonArraySetting
    #  arguments:
    #    - '@aw.settings.storage'
    #    - 'moy_sklad.products.folders'
    #    - 'Папки, из которых будут извелкаться товары при синхронизации'
    #    - { 0: 'Сыр в КГ' }
    #  tags:
    #    - { name: aw.setting }
