services:
    store.setting.abandoned_cart:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      public: false
      autowire: false
      arguments:
       - '@aw.settings.storage'
       - abandoned_cart_age
       - Возраст корзины в днях, при котором она считается брошенной.
       - 30
      tags:
        - { name: aw.setting }

    store.setting.default_order_status:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
       - '@aw.settings.storage'
       - '@store.order_status.repository'
       - default_order_status
       - Статус по умолчанию для нового заказа.
      tags:
        - { name: aw.setting }

    store.setting.default_order_payment_status:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
       - '@aw.settings.storage'
       - '@store.order_payment_status.repository'
       - default_order_payment_status
       - Статус оплаты по умолчанию для нового заказа.
      tags:
        - { name: aw.setting }

    store.setting.facebook_link:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'facebook_link'
        - 'Ссылка Facebook'
        - ~
      tags:
        - { name: aw.setting }

    store.setting.vk_link:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'vk_link'
        - 'Ссылка Вконтакте'
        - ~
      tags:
        - { name: aw.setting }

    store.setting.instagram_link:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'instagram_link'
        - 'Ссылка Instagram'
        - ~
      tags:
        - { name: aw.setting }

    store.setting.root_catalog_redirect:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'root_catalog_redirect'
        - 'Алиас, на который будет производиться редирект при попытке зайти в корневой радел каталога'
        - 'syr'
      tags:
        - { name: aw.setting }

    store.setting.cheese_hardness_property:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
        - '@aw.settings.storage'
        - '@store.product.attribute.repository'
        - 'cheese_hardness_property'
        - 'Свойство твердости для фильтра по сырам'
      tags:
        - { name: aw.setting }


    store.setting.cheese_mold_property:
      class: Accurateweb\SettingBundle\Model\Setting\EntitySetting
      arguments:
        - '@aw.settings.storage'
        - '@store.product.attribute.repository'
        - 'cheese_mold_property'
        - 'Свойство вида плесени для фильтра по сырам'
      tags:
        - { name: aw.setting }

    #store.setting.synchronization.moy_sklad.products.folder:
    #  class: Accurateweb\SettingBundle\Model\Setting\JsonArraySetting
    #  arguments:
    #    - '@aw.settings.storage'
    #    - 'moy_sklad.products.folders'
    #    - 'Папки, из которых будут извелкаться товары при синхронизации'
    #    - { 0: 'Сыр в КГ' }
    #  tags:
    #    - { name: aw.setting }

    store.setting.contact_email:
      class: Accurateweb\SettingBundle\Model\Setting\StringSetting
      arguments:
        - '@aw.settings.storage'
        - 'contact_email'
        - 'Контактный e-mail'
        - 'info@rezhano.ru'
      tags:
        - { name: aw.setting }
