aw_email_templating:
  templating:
    loader: aw_email_templating.template.loader.doctrine
    entity: StoreBundle\Entity\Messaging\EmailTemplate
    images_as_attachment: true
  email_templates:
    checkout:
      description: 'Уведомление покупателю об успешном оформлении заказа'
      variables:
        customer_name: { description: "ФИО покупателя" }
        order_number: { description: "Номер заказа" }
        customer_phone: { description: "Телефон покупателя" }
        customer_email: { description: "Email покупателя" }
        payment_method: { description: "Способ оплаты" }
        shipping_method: { description: "Способ доставки" }
        shipping_address: { description: "Адрес доставки (включая город и индекс)" }
        subtotal: { description: "Стоимость товаров в заказе" }
        shipping_cost: { description: "Стоимость доставки" }
        fee: { description: "Комиссия" }
        total: { description: "Стоимость заказа" }
        order_items: { description: "Состав заказа" }
        social_items: { description: "Ссылки на социальные сети" }
      defaults:
        subject: "Заказ в Интернет-магазине Режано"
        body: |
                <table style="width: 100%%; min-width: 700px; background: #fff;" border="0" cellspacing="0" cellpadding="0"
                align="center">
                <tbody>
                <tr align="center">
                <td align="center">
                <table style="padding-top: 20px; width: 600px; background-color: #f3f3f3; color: #ffffff; font-family: Arial, Helvetica, sans-serif;" border="0" cellspacing="0" cellpadding="0" align="center">
                <tbody>
                <tr>
                <img src="/images/mail/header.png" style="margin-bottom: -20px"/>
                </tr>
                <tr>
                <td style="padding: 30px 35px 0 35px; color: #ffffff;" valign="top" width="532">
                <p style="margin: 0; font-size: 24px; color: #000; margin-bottom: 5px;"><span style="color: #000;">Спасибо, мы получили ваш заказ!</span>
                </p>
                <p style="margin: 0; font-size: 14px; color: #000; margin-bottom: 5px;"><span style="color: #000;">В ближайшее рабочее время с вами свяжется наш менеджер</span>
                </p>
                <p style="margin: 0; font-size: 14px; font-weight: bold; color: #000; margin-bottom: 5px;"><span
                style="color: #000;">№ заказ %%order_number%% </span></p>
                %%order_items%%
                </td>
                </tr>
                </tbody>
                </table>
                <table style="width: 600px; background-color: #f3f3f3; color: #ffffff; font-family: Arial, Helvetica, sans-serif;"
                border="0" cellspacing="0" cellpadding="0" align="center">
                <tbody>
                <tr>
                <td style="padding: 30px 35px 30px 35px; color: #ffffff;" valign="top" width="532">
                <p style="margin: 0; font-size: 14px; font-weight: bold; color: #000; margin-bottom: 5px;"><span
                style="color: #000;">Итого: %%total%%</span></p>
                <p style="margin: 0; font-size: 14px; color: #000; margin-bottom: 5px; width: 520px;"><span
                style="color: #000; line-height: 21px;">окончательная цена заказа может немного измениться, ведь каждый кусочек
                бережно отрезается в ручную, и вес может отличаться.</span>
                </p>
                </td>
                </tr>
                </tbody>
                </table>
                <table
                style="margin-top: 11px; margin-bottom: 11px; width: 600px; background-color: #f3f3f3; color: #ffffff; font-family: Arial, Helvetica, sans-serif;"
                border="0" cellspacing="0" cellpadding="0" align="center">
                <tbody>
                <tr>
                <td style="padding: 30px 35px 30px 35px; color: #ffffff;" valign="top" width="532">
                <p style="margin: 0; font-size: 14px; font-weight: bold; color: #000; margin-bottom: 5px;"><span
                style="color: #000;">Данные покупателя</span></p>
                <table style="width: 100%%; border-collapse: collapse">
                <tbody>
                <tr class="Stil1" style="margin: 0; font-size: 14px; color: #000;">
                <td width="96" style="padding: 0;">
                <p>ФИО:</p>
                </td>
                <td style="padding: 0;"><p style="margin-bottom: 5px;">%%customer_name%%</p></td>
                </tr>
                <tr class="Stil1" style="margin: 0; font-size: 14px; color: #000;">
                <td width="96" style="padding: 0;"><p>Адрес:&nbsp;</p></td>
                <td style="padding: 0;"><p style="margin-bottom: 5px;">%%shipping_address%%</p></td>
                </tr>
                <tr class="Stil1" style="margin: 0; font-size: 14px; color: #000;">
                <td width="96" style="padding: 0;"><p>Телефон:</p></td>
                <td style="padding: 0;"><p style="margin-bottom: 5px;">%%customer_phone%%</p></td>
                </tr>
                <tr class="Stil1" style="margin: 0; font-size: 14px; color: #000;">
                <td width="96" style="padding: 0;"><p>E-mail:</p></td>
                <td style="padding: 0;"><p style="margin-bottom: 5px;">%%customer_email%%</p></td>
                </tr>
                </tbody>
                </table>
                </td>
                </tr>
                </tbody>
                </table>
                <table
                style="margin-top: 11px; width: 600px; background-color: #f3f3f3; color: #ffffff; font-family: Arial, Helvetica, sans-serif;"
                border="0" cellspacing="0" cellpadding="0" align="center">
                <tbody>
                <tr>
                <td style="padding: 30px 35px 30px 35px; color: #ffffff;" valign="top" width="532">
                <p style="margin: 0; font-size: 14px; color: #000; margin-bottom: 25px; width: 520px; line-height: 21px">
                <span style="color: #000;">Проверьте, пожалуйста, состав заказа и данные получателя. Если вдруг вы заметили какую-то ошибку, обязательно напишите или позвоните мне!</span>
                </p>
                <table style="width: 100%%; border-collapse: collapse">
                <tbody>
                <tr>
                <td style="vertical-align: top; padding: 0;">
                <table style="width: 100%%;">
                <tbody>
                <tr>
                <td style="margin-bottom: 3px;">
                <p style="margin: 0; font-size: 14px; font-weight: bold; color: #000; margin-bottom: 5px;"><span
                style="color: #000;">Юля Лещикова</span></p>
                </td>
                </tr>
                <tr class="Stil1" style="margin: 0; font-size: 14px; color: #000;">
                <td width="96" style="padding: 0; margin-bottom: 3px;">
                <p style="margin-bottom: 5px;">Ваш сырный менеджер</p>
                </td>
                </tr>
                <tr class="Stil1" style="margin: 0; font-size: 14px; color: #000;">
                <td width="96" style="padding: 0; margin-bottom: 3px;">
                <p style="margin-bottom: 5px;">info@rezhano.ru&nbsp;</p>
                </td>
                </tr>
                <tr class="Stil1" style="margin: 0; font-size: 14px; color: #000;">
                <td width="96" style="padding: 0; margin-bottom: 3px;">
                <p style="margin-bottom: 5px;">Телефоне: +7 (902) 234-32-32</p>
                </td>
                </tr>
                </tbody>
                </table>
                </td>
                <td align="right">
                <img width="104" src="/images/mail/manager.png" alt="">
                </td>
                </tr>
                </tbody>
                </table>
                </td>
                </tr>
                </tbody>
                </table>
                <table style="width: 600px; background-color: #ffffff; color: #ffffff; font-family: Arial, Helvetica, sans-serif;"
                border="0" cellspacing="0" cellpadding="0" align="center">
                <tbody>
                <tr>
                <td>
                <table>
                <tbody>
                <tr>
                <td style="width: 60%%">
                <table>
                <tr>
                <td style="padding: 25px 35px 30px 35px; color: #ffffff;" valign="top">
                <p style="margin: 0; font-size: 14px; color: #000; margin-bottom: 5px;"><span
                style="color: #000; line-height: 21px;">Наша почта: info@rezhano.ru</span></p>
                <p style="margin: 0; font-size: 14px; color: #000; margin-bottom: 5px;"><span
                style="color: #000; line-height: 21px;">+7 (343) 207-76-66 — по всем вопросам</span></p>
                <p style="margin: 0; font-size: 14px; color: #000; margin-bottom: 5px;"><a
                href="https://rezhano.ru/"><span style="color: #000; line-height: 21px;">www.rezhano.ru</span></a>
                </p>
                </td>
                </tr>
                </table>
                </td>
                <td style="width: 40%%" valign="top">
                <table align="right">
                <tr>
                %%social_items%%
                </tr>
                </table>
                </td>
                </tr>
                <tr>
                <td style="padding: 0 35px 30px 35px;">
                <p style="margin: 0; font-size: 14px; color: #000; margin-bottom: 5px;"><span
                style="color: #b2b2b2; line-height: 21px;">© Сыроварня «Режано»</span></p>
                </td>
                <td style="padding: 0 0 30px 35px;" align="right">
                <a href="https://rezhano.ru/" target="_blank">
                <img src="/images/svg/logo-mail.svg" alt="" width="131">
                </a>
                </td>
                </tr>
                </tbody>
                </table>
                </td>
                </tr>
                </tbody>
                </table>
                </td>
                </tr>
                </tbody>
                </table>

    checkout_operator:
      description: 'Уведомление оператору об успешном оформлении заказа'
      variables:
        customer_name: { description: "ФИО покупателя" }
        order_number: { description: "Номер заказа" }
        customer_phone: { description: "Телефон покупателя" }
        customer_email: { description: "Email покупателя" }
        payment_method: { description: "Способ оплаты" }
        shipping_method: { description: "Способ доставки" }
        shipping_address: { description: "Адрес доставки (включая город и индекс)" }
        subtotal: { description: "Стоимость товаров в заказе" }
        shipping_cost: { description: "Стоимость доставки" }
        fee: { description: "Комиссия" }
        total: { description: "Стоимость заказа" }
        order_items: { description: "Состав заказа" }
      defaults:
        subject: "Заказ в Интернет-магазине Store"
        body: |
          %%customer_name%% оформил(а) заказ %%order_number%%.

    product_question_operator:
      description: "Уведомление оператору о вопросе к товару"
      variables:
        product_name: { description: "Название товара" }
        product_sku: { description: "Артикул товара" }
        customer_name: { description: "ФИО клиента" }
        customer_email: { description: "Email клиента" }
        question: { description: "Текст вопроса" }
      defaults:
        subject: "Вопрос о товаре «%%product_name%%»"
        body: |
          От %%customer_name%% (%%customer_email%%) получен вопрос о товаре «%%product_name%%» (артикул %%product_sku%%)

          Текст вопроса: «%%question%%».

    user_question_operator:
      description: "Уведомление оператору о вопросе от пользователя"
      variables:
        customer_name: { description: "ФИО клиента" }
        customer_email: { description: "Email клиента" }
        question: { description: "Текст вопроса" }
      defaults:
        subject: "Вопрос от клиента %%customer_name%%"
        body: |
          От %%customer_name%% (%%customer_email%%) получен вопрос.

          Текст вопроса: «%%question%%».

    question_answer:
      description: "Ответ пользователю, задавшему вопрос на сайте"
      variables:
        customer_name: { description: "ФИО клиента" }
        customer_email: { description: "Email клиента" }
        customer_phone: { description: "Телефон клиента" }
        question: { description: "Текст вопроса" }
      defaults:
        subject: "Ответ на вопрос"
        body: |
          %%customer_name%%!
          Ответ на Ваш вопрос «%%question%%»:
#    checkout_1click_operator:
#      description: "Уведомление оператору о заказе в «1 клик»"
#      variables:
#        product_name: { description: "Название товара" }
#        product_sku: { description: "Артикул товара" }
#        product_url: { description: "URL страницы товара" }
#        product_phone: { description: "Телефон покупателя" }
#      defaults:
#        subject: "Заказ «1 клик»"
#        body: |
#          Оформлен заказ в «1 клик» на товар %%product_sku%% <a href="%%product_url%%">%%product_name%%</a>. Номер телефона покупателя %%customer_phone%%.
#
#    checkout_preorder_operator:
#      description: "Уведомление оператору о предзаказе"
#      variables:
#        product_name: { description: "Название товара" }
#        product_sku: { description: "Артикул товара" }
#        product_url: { description: "URL страницы товара" }
#        product_phone: { description: "Телефон покупателя" }
#      defaults:
#        subject: "Предзаказ"
#        body: |
#          Оформлен предзаказ на товар %%product_sku%% <a href="%%product_url%%">%%product_name%%</a>. Номер телефона покупателя %%customer_phone%%.

    user_registration_confirm:
      description: "Подтверждение регистрации"
      variables:
        username: { description: "Имя пользователя" }
        confirmation_url: { description: "Ссылка на страницу подтверждения сброса пароля" }
      defaults:
        body: |
          Здравствуйте, %%username%%.

          Чтобы подтвердить регистрацию, пройдите по ссылке: <a href="%%confirmation_url%%">%%confirmation_url%%</a>
        subject: "Подтверждение регистрации"

    user_password_reset_request:
      description: "Запрос восстановления пароля"
      variables:
        username: { description: "Имя пользователя" }
        confirmation_url: { description: "Ссылка на страницу подтверждения сброса пароля" }
      defaults:
        body: |
          Здравствуйте, %%username%%.

          Чтобы сбросить Ваш пароль, пройдите по ссылке: <a href="%%confirmation_url%%">%%confirmation_url%%</a>
        subject: "Восстановление пароля"

    user_password_reset_completed:
      description: "Уведомление об успешном сбросе пароля"
      variables:
        username: { description: "Имя пользователя" }
      defaults:
        body: |
          Здравствуйте, %%username%%.

          Ваш пароль был успешно изменен.
        subject: "Ваш пароль был изменен"

    customer_question_operator:
      description: 'Уведомление о новом вопросе покупателя'
      variables:
        fio: { description: 'Имя пользователя' }
        question: { description: 'Вопрос' }
        date: { description: 'Дата создания' }
      defaults:
        body: |
          <h3>Покупатель %%fio%% задал вопрос:<h3>
          <p>%%question%%</p>
        subject: 'Покупатель %%fio%% задал вопрос'

    customer_question_answer:
      description: 'Уведомление пользователя об ответе на его вопрос'
      variables:
        question: { description: 'Вопрос' }
        date_create: { description: 'Дата создания вопроса' }
        message: { description: 'Ответ' }
        date_answer: { description: 'Дата ответа' }
        fio: { description: 'ФИО пользователя' }
        email: { description: 'Email пользователя' }
      defaults:
        body: |
          <h3>%%fio%%, на ваш вопрос был дан ответ<h3>
          <p>%%question%%</p>
          <p>%%message%%</p>
        subject: 'На ваш вопрос был дан ответ'