accurateweb_logistic:
    resource: "@AccuratewebLogisticBundle/Resources/config/routing.yml"
    prefix:   /

Store:
  resource: "@StoreBundle/Resources/config/routing.yml"
  prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security_login:
  path: /login
  methods: [GET, POST]
  defaults: { _controller: StoreBundle:Profile\Security:login }

fos_user_security_check:
  path: /login_check
  methods: [POST]
  defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
  path: /logout
  methods: [GET, POST]
  defaults: { _controller: FOSUserBundle:Security:logout }

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

user_api_register:
  path: /api/user
  methods: [POST]
  defaults: { _controller: StoreBundle:Profile/Registration:register }
  condition: "request.isXmlHttpRequest()"

user_api_edit:
  path: /api/user
  methods: [PUT]
  defaults: { _controller: FOSUserBundle:Profile:edit }
  condition: "request.isXmlHttpRequest()"

user_api_document:
  path: /api/user/upload/{typeId}
  methods: [PUT, POST]
  defaults: { _controller: StoreBundle:Profile\Registration:uploadRegisterDocument }

fos_user_registration_register:
  path: /registration
  defaults: { _controller: StoreBundle:Profile/Registration:register }

fos_user_registration_success:
  path: /registration/success
  defaults: { _controller: StoreBundle:Profile/Registration:success }

fos_user_registration_check_email:
  path: /registration/check-email
  defaults: { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
  path: /registration/confirm/{token}
  defaults: { _controller: FOSUserBundle:Registration:confirm }

fos_user_registration_confirmed:
  path: /registration/confirmed
  defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /passwordreset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /cabinet

accurateweb_media:
    resource: "@AccuratewebMediaBundle/Resources/config/routing.yml"
    prefix: /media

accurateweb_media_admin:
    resource: "@AccuratewebMediaBundle/Resources/config/admin.routing.yml"
    prefix: /admin/media

article_show:
  path:      /{slug}
  defaults:  { _controller: StoreBundle:Article:show }

redcode_tree:
    resource: "@RedCodeTreeBundle/Resources/config/routing.yml"
    prefix:   /admin

click_zone_edit:
  path:     /clickzones/{alias}
  defaults: { _controller: ContentHotspotBundle:ContentHotspot:edit }
  methods: [POST]