# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_JURIDICAL: ROLE_USER
        ROLE_ENTREPRENEUR: ROLE_USER
        ROLE_INDIVIDUAL: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                failure_handler: store.security.authentication_handler
                success_handler: store.security.authentication_handler
                #csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            logout:       true
            anonymous:    true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_decision_manager:
      #Если все Voter сказали Accept
      strategy: unanimous

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration/success, role: ROLE_USER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/cabinet, role: ROLE_USER }
        - { path: ^/cabinet.*, role: ROLE_USER }
        - { path: ^/favorites, role: ROLE_USER }
        - { path: ^/checkout, role: ROLE_USER }
        - { path: ^/checkout.*, role: ROLE_USER }
#        - { path: ^/cart.*, role: ROLE_USER }
        - { path: ^/api/cabinet, role: ROLE_USER }
        - { path: ^/api/notice.*, role: ROLE_USER }
        - { path: ^/api/dialog.*, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/media/gallery/product-photo/.*/upload, role: ROLE_ADMIN }