# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_SONATA_ALL]
        ROLE_OPERATOR:
          - ROLE_USER
          - ROLE_SONATA_ADMIN
          - ROLE_MAIN_ADMIN_ORDER_LIST
          - ROLE_MAIN_ADMIN_ORDER_EDIT
          - ROLE_MAIN_ADMIN_ORDER_VIEW
          - ROLE_MAIN_ADMIN_ORDER_ITEM_LIST
          - ROLE_MAIN_ADMIN_ORDER_ITEM_EDIT
          - ROLE_MAIN_ADMIN_ORDER_ITEM_CREATE
          - ROLE_MAIN_ADMIN_ORDER_ITEM_VIEW
          - ROLE_MAIN_ADMIN_ORDER_ITEM_DELETE
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_JURIDICAL: ROLE_USER
        ROLE_ENTREPRENEUR: ROLE_USER
        ROLE_INDIVIDUAL: ROLE_USER
        ROLE_SONATA_ALL:
         - ROLE_SONATA_LIST
         - ROLE_SONATA_VIEW
         - ROLE_SONATA_CREATE
         - ROLE_SONATA_EDIT
         - ROLE_SONATA_DELETE
        ROLE_SONATA_LIST:
         - ROLE_APP_ADMIN_TEXT_SPECIALOFFER_LIST
         - ROLE_APP_ADMIN_MENU_MENUITEM_LIST
         - ROLE_MAIN_ADMIN_NEWS_LIST
         - ROLE_MAIN_ADMIN_ARTICLE_LIST
         - ROLE_MAIN_ADMIN_ORDER_LIST
         - ROLE_MAIN_ADMIN_ORDER_ITEM_LIST
         - ROLE_MAIN_ADMIN_ORDER_STATUS_LIST
         - ROLE_MAIN_ADMIN_ORDER_PAYMENT_STATUS_LIST
         - ROLE_MAIN_ADMIN_ORDER_STATUS_NOTIFICATION_TEMPLATE_LIST
         - ROLE_MAIN_ADMIN_BRAND_LIST
         - ROLE_MAIN_ADMIN_CATALOG_PRODUCT_LIST
         - ROLE_MAIN_ADMIN_USER_LIST
         - ROLE_APP_ADMIN_CATALOG_TAXON_LIST
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTES_LIST
         - ROLE_APP_ADMIN_PRODUCTS_TYPE_LIST
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTEVALUE_LIST
         - ROLE_APP_ADMIN_PRODUCTS_PRODUCTATTRIBUTE_VALUETOPRODUCT_LIST
         - ROLE_MAIN_ADMIN_PAYMENT_METHOD_LIST
         - ROLE_APP_ADMIN_STORE_ORDER_STATUS_REASON_LIST
         - ROLE_STORE_ADMIN_CUSTOMER_MESSAGE_LIST
         - ROLE_STORE_ADMIN_STORE_STORE_ADMIN_LIST
         - ROLE_STORE_ADMIN_TESTIMONIAL_LIST
         - ROLE_STORE_ADMIN_EXCURSION_BANNER_LIST
         - ROLE_STORE_ADMIN_EXCURSION_TEASER_LIST
         - ROLE_STORE_ADMIN_ABOUT_US_GALLERY_LIST
         - ROLE_APP_ADMIN_CHEESE_STORY_LIST
         - ROLE_APP_ADMIN_PARTNER_LIST
         - ROLE_APP_ADMIN_PROMO_BANNER_LIST
         - ROLE_APP_ADMIN_SHIP_LIST
         - ROLE_APP_ADMIN_PICKUP_LIST
         - ROLE_APP_ADMIN_USER_QUSTION_LIST
         - ROLE_APP_HOME_BANNER_ADMIN_LIST
         - ROLE_APP_ADMIN_CONTACT_PHONE_LIST
         - ROLE_AW_EMAIL_TEMPLATE_ADMIN_EMAIL_TEMPLATE_LIST
         - ROLE_MAIN_ADMIN_SETTINGS_LIST
         - ROLE_AW_CLICKZONE_ADMIN_CLICKZONE_LIST
         - ROLE_AW_LOGISTIC_WAREHOUSE_ADMIN_LIST
         - ROLE_AW_LOGISTIC_CITY_ADMIN_LIST
         - ROLE_AW_LOGISTIC_PICKUP_POINT_ADMIN_LIST
         - ROLE_AW_LOGISTIC_PRODUCT_STOCK_ADMIN_LIST
        ROLE_SONATA_VIEW:
         - ROLE_APP_ADMIN_TEXT_SPECIALOFFER_VIEW
         - ROLE_APP_ADMIN_MENU_MENUITEM_VIEW
         - ROLE_MAIN_ADMIN_NEWS_VIEW
         - ROLE_MAIN_ADMIN_ARTICLE_VIEW
         - ROLE_MAIN_ADMIN_ORDER_VIEW
         - ROLE_MAIN_ADMIN_ORDER_ITEM_VIEW
         - ROLE_MAIN_ADMIN_ORDER_STATUS_VIEW
         - ROLE_MAIN_ADMIN_ORDER_PAYMENT_STATUS_VIEW
         - ROLE_MAIN_ADMIN_ORDER_STATUS_NOTIFICATION_TEMPLATE_VIEW
         - ROLE_MAIN_ADMIN_BRAND_VIEW
         - ROLE_MAIN_ADMIN_CATALOG_PRODUCT_VIEW
         - ROLE_MAIN_ADMIN_USER_VIEW
         - ROLE_APP_ADMIN_CATALOG_TAXON_VIEW
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTES_VIEW
         - ROLE_APP_ADMIN_PRODUCTS_TYPE_VIEW
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTEVALUE_VIEW
         - ROLE_APP_ADMIN_PRODUCTS_PRODUCTATTRIBUTE_VALUETOPRODUCT_VIEW
         - ROLE_MAIN_ADMIN_PAYMENT_METHOD_VIEW
         - ROLE_APP_ADMIN_STORE_ORDER_STATUS_REASON_VIEW
         - ROLE_STORE_ADMIN_CUSTOMER_MESSAGE_VIEW
         - ROLE_STORE_ADMIN_STORE_STORE_ADMIN_VIEW
         - ROLE_STORE_ADMIN_TESTIMONIAL_VIEW
         - ROLE_STORE_ADMIN_EXCURSION_BANNER_VIEW
         - ROLE_STORE_ADMIN_EXCURSION_TEASER_VIEW
         - ROLE_STORE_ADMIN_ABOUT_US_GALLERY_VIEW
         - ROLE_APP_ADMIN_CHEESE_STORY_VIEW
         - ROLE_APP_ADMIN_PARTNER_VIEW
         - ROLE_APP_ADMIN_PROMO_BANNER_VIEW
         - ROLE_APP_ADMIN_SHIP_VIEW
         - ROLE_APP_ADMIN_PICKUP_VIEW
         - ROLE_APP_ADMIN_USER_QUSTION_VIEW
         - ROLE_APP_HOME_BANNER_ADMIN_VIEW
         - ROLE_APP_ADMIN_CONTACT_PHONE_VIEW
         - ROLE_AW_EMAIL_TEMPLATE_ADMIN_EMAIL_TEMPLATE_VIEW
         - ROLE_MAIN_ADMIN_SETTINGS_VIEW
         - ROLE_AW_CLICKZONE_ADMIN_CLICKZONE_VIEW
         - ROLE_AW_LOGISTIC_WAREHOUSE_ADMIN_VIEW
         - ROLE_AW_LOGISTIC_CITY_ADMIN_VIEW
         - ROLE_AW_LOGISTIC_PICKUP_POINT_ADMIN_VIEW
         - ROLE_AW_LOGISTIC_PRODUCT_STOCK_ADMIN_VIEW
        ROLE_SONATA_CREATE:
         - ROLE_APP_ADMIN_TEXT_SPECIALOFFER_CREATE
         - ROLE_APP_ADMIN_MENU_MENUITEM_CREATE
         - ROLE_MAIN_ADMIN_NEWS_CREATE
         - ROLE_MAIN_ADMIN_ARTICLE_CREATE
         - ROLE_MAIN_ADMIN_ORDER_CREATE
         - ROLE_MAIN_ADMIN_ORDER_ITEM_CREATE
         - ROLE_MAIN_ADMIN_ORDER_STATUS_CREATE
         - ROLE_MAIN_ADMIN_ORDER_PAYMENT_STATUS_CREATE
         - ROLE_MAIN_ADMIN_ORDER_STATUS_NOTIFICATION_TEMPLATE_CREATE
         - ROLE_MAIN_ADMIN_BRAND_CREATE
         - ROLE_MAIN_ADMIN_CATALOG_PRODUCT_CREATE
         - ROLE_MAIN_ADMIN_USER_CREATE
         - ROLE_APP_ADMIN_CATALOG_TAXON_CREATE
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTES_CREATE
         - ROLE_APP_ADMIN_PRODUCTS_TYPE_CREATE
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTEVALUE_CREATE
         - ROLE_APP_ADMIN_PRODUCTS_PRODUCTATTRIBUTE_VALUETOPRODUCT_CREATE
         - ROLE_MAIN_ADMIN_PAYMENT_METHOD_CREATE
         - ROLE_APP_ADMIN_STORE_ORDER_STATUS_REASON_CREATE
         - ROLE_STORE_ADMIN_CUSTOMER_MESSAGE_CREATE
         - ROLE_STORE_ADMIN_STORE_STORE_ADMIN_CREATE
         - ROLE_STORE_ADMIN_TESTIMONIAL_CREATE
         - ROLE_STORE_ADMIN_EXCURSION_BANNER_CREATE
         - ROLE_STORE_ADMIN_EXCURSION_TEASER_CREATE
         - ROLE_STORE_ADMIN_ABOUT_US_GALLERY_CREATE
         - ROLE_APP_ADMIN_CHEESE_STORY_CREATE
         - ROLE_APP_ADMIN_PARTNER_CREATE
         - ROLE_APP_ADMIN_PROMO_BANNER_CREATE
         - ROLE_APP_ADMIN_SHIP_CREATE
         - ROLE_APP_ADMIN_PICKUP_CREATE
         - ROLE_APP_ADMIN_USER_QUSTION_CREATE
         - ROLE_APP_HOME_BANNER_ADMIN_CREATE
         - ROLE_APP_ADMIN_CONTACT_PHONE_CREATE
         - ROLE_AW_EMAIL_TEMPLATE_ADMIN_EMAIL_TEMPLATE_CREATE
         - ROLE_MAIN_ADMIN_SETTINGS_CREATE
         - ROLE_AW_CLICKZONE_ADMIN_CLICKZONE_CREATE
         - ROLE_AW_LOGISTIC_WAREHOUSE_ADMIN_CREATE
         - ROLE_AW_LOGISTIC_CITY_ADMIN_CREATE
         - ROLE_AW_LOGISTIC_PICKUP_POINT_ADMIN_CREATE
         - ROLE_AW_LOGISTIC_PRODUCT_STOCK_ADMIN_CREATE
        ROLE_SONATA_EDIT:
         - ROLE_APP_ADMIN_TEXT_SPECIALOFFER_EDIT
         - ROLE_APP_ADMIN_MENU_MENUITEM_EDIT
         - ROLE_MAIN_ADMIN_NEWS_EDIT
         - ROLE_MAIN_ADMIN_ARTICLE_EDIT
         - ROLE_MAIN_ADMIN_ORDER_EDIT
         - ROLE_MAIN_ADMIN_ORDER_ITEM_EDIT
         - ROLE_MAIN_ADMIN_ORDER_STATUS_EDIT
         - ROLE_MAIN_ADMIN_ORDER_PAYMENT_STATUS_EDIT
         - ROLE_MAIN_ADMIN_ORDER_STATUS_NOTIFICATION_TEMPLATE_EDIT
         - ROLE_MAIN_ADMIN_BRAND_EDIT
         - ROLE_MAIN_ADMIN_CATALOG_PRODUCT_EDIT
         - ROLE_MAIN_ADMIN_USER_EDIT
         - ROLE_APP_ADMIN_CATALOG_TAXON_EDIT
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTES_EDIT
         - ROLE_APP_ADMIN_PRODUCTS_TYPE_EDIT
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTEVALUE_EDIT
         - ROLE_APP_ADMIN_PRODUCTS_PRODUCTATTRIBUTE_VALUETOPRODUCT_EDIT
         - ROLE_MAIN_ADMIN_PAYMENT_METHOD_EDIT
         - ROLE_APP_ADMIN_STORE_ORDER_STATUS_REASON_EDIT
         - ROLE_STORE_ADMIN_CUSTOMER_MESSAGE_EDIT
         - ROLE_STORE_ADMIN_STORE_STORE_ADMIN_EDIT
         - ROLE_STORE_ADMIN_TESTIMONIAL_EDIT
         - ROLE_STORE_ADMIN_EXCURSION_BANNER_EDIT
         - ROLE_STORE_ADMIN_EXCURSION_TEASER_EDIT
         - ROLE_STORE_ADMIN_ABOUT_US_GALLERY_EDIT
         - ROLE_APP_ADMIN_CHEESE_STORY_EDIT
         - ROLE_APP_ADMIN_PARTNER_EDIT
         - ROLE_APP_ADMIN_PROMO_BANNER_EDIT
         - ROLE_APP_ADMIN_SHIP_EDIT
         - ROLE_APP_ADMIN_PICKUP_EDIT
         - ROLE_APP_ADMIN_USER_QUSTION_EDIT
         - ROLE_APP_HOME_BANNER_ADMIN_EDIT
         - ROLE_APP_ADMIN_CONTACT_PHONE_EDIT
         - ROLE_AW_EMAIL_TEMPLATE_ADMIN_EMAIL_TEMPLATE_EDIT
         - ROLE_MAIN_ADMIN_SETTINGS_EDIT
         - ROLE_AW_CLICKZONE_ADMIN_CLICKZONE_EDIT
         - ROLE_AW_LOGISTIC_WAREHOUSE_ADMIN_EDIT
         - ROLE_AW_LOGISTIC_CITY_ADMIN_EDIT
         - ROLE_AW_LOGISTIC_PICKUP_POINT_ADMIN_EDIT
         - ROLE_AW_LOGISTIC_PRODUCT_STOCK_ADMIN_EDIT
        ROLE_SONATA_DELETE:
         - ROLE_APP_ADMIN_TEXT_SPECIALOFFER_DELETE
         - ROLE_APP_ADMIN_MENU_MENUITEM_DELETE
         - ROLE_MAIN_ADMIN_NEWS_DELETE
         - ROLE_MAIN_ADMIN_ARTICLE_DELETE
         - ROLE_MAIN_ADMIN_ORDER_DELETE
         - ROLE_MAIN_ADMIN_ORDER_ITEM_DELETE
         - ROLE_MAIN_ADMIN_ORDER_STATUS_DELETE
         - ROLE_MAIN_ADMIN_ORDER_PAYMENT_STATUS_DELETE
         - ROLE_MAIN_ADMIN_ORDER_STATUS_NOTIFICATION_TEMPLATE_DELETE
         - ROLE_MAIN_ADMIN_BRAND_DELETE
         - ROLE_MAIN_ADMIN_CATALOG_PRODUCT_DELETE
         - ROLE_MAIN_ADMIN_USER_DELETE
         - ROLE_APP_ADMIN_CATALOG_TAXON_DELETE
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTES_DELETE
         - ROLE_APP_ADMIN_PRODUCTS_TYPE_DELETE
         - ROLE_APP_ADMIN_PRODUCTS_ATTRIBUTEVALUE_DELETE
         - ROLE_APP_ADMIN_PRODUCTS_PRODUCTATTRIBUTE_VALUETOPRODUCT_DELETE
         - ROLE_MAIN_ADMIN_PAYMENT_METHOD_DELETE
         - ROLE_APP_ADMIN_STORE_ORDER_STATUS_REASON_DELETE
         - ROLE_STORE_ADMIN_CUSTOMER_MESSAGE_DELETE
         - ROLE_STORE_ADMIN_STORE_STORE_ADMIN_DELETE
         - ROLE_STORE_ADMIN_TESTIMONIAL_DELETE
         - ROLE_STORE_ADMIN_EXCURSION_BANNER_DELETE
         - ROLE_STORE_ADMIN_EXCURSION_TEASER_DELETE
         - ROLE_STORE_ADMIN_ABOUT_US_GALLERY_DELETE
         - ROLE_APP_ADMIN_CHEESE_STORY_DELETE
         - ROLE_APP_ADMIN_PARTNER_DELETE
         - ROLE_APP_ADMIN_PROMO_BANNER_DELETE
         - ROLE_APP_ADMIN_SHIP_DELETE
         - ROLE_APP_ADMIN_PICKUP_DELETE
         - ROLE_APP_ADMIN_USER_QUSTION_DELETE
         - ROLE_APP_HOME_BANNER_ADMIN_DELETE
         - ROLE_APP_ADMIN_CONTACT_PHONE_DELETE
         - ROLE_AW_EMAIL_TEMPLATE_ADMIN_EMAIL_TEMPLATE_DELETE
         - ROLE_MAIN_ADMIN_SETTINGS_DELETE
         - ROLE_AW_CLICKZONE_ADMIN_CLICKZONE_DELETE
         - ROLE_AW_LOGISTIC_WAREHOUSE_ADMIN_DELETE
         - ROLE_AW_LOGISTIC_CITY_ADMIN_DELETE
         - ROLE_AW_LOGISTIC_PICKUP_POINT_ADMIN_DELETE
         - ROLE_AW_LOGISTIC_PRODUCT_STOCK_ADMIN_DELETE



    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                failure_handler: store.security.authentication_handler
                success_handler: store.security.authentication_handler
                #csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            logout:       true
            anonymous:    true
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_decision_manager:
      #Если все Voter сказали Accept
      strategy: unanimous

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration/success, role: ROLE_USER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/cabinet, role: ROLE_USER }
        - { path: ^/cabinet.*, role: ROLE_USER }
#        - { path: ^/favorites, role: ROLE_USER }
#        - { path: ^/checkout, role: ROLE_USER }
#        - { path: ^/checkout.*, role: ROLE_USER }
#        - { path: ^/cart.*, role: ROLE_USER }
        - { path: ^/api/cabinet, role: ROLE_USER }
        - { path: ^/api/notice.*, role: ROLE_USER }
        - { path: ^/api/dialog.*, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_SONATA_ADMIN }
        - { path: ^/media/gallery/product-photo/.*/upload, role: ROLE_ADMIN }