services:
  aw.moysklad:
    class: Accurateweb\MoyskladIntegrationBundle\Model\MoyskladManager
    arguments:
      - '@store.setting.moy_sklad_login'
      - '@store.setting.moy_sklad_password'
    public: false

  moysklad.order.checkout.moysklad_queue:
    class: Accurateweb\MoyskladIntegrationBundle\EventListener\OrderCheckoutMoyskladQueue
    arguments:
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: kernel.event_listener, event: store.order.checkout, method: onOrderCheckout }

  moysklad.sender:
    class: Accurateweb\MoyskladIntegrationBundle\Service\MoyskladOrderSender
    arguments:
      - '@aw.moysklad'
      - '@event_dispatcher'
      - '%moysklad_organisation_id%'
      - '@aw.settings.manager'