<?php

namespace StoreBundle\Repository\Store;
use Doctrine\Common\Collections\Collection;
use StoreBundle\Entity\Store\Store;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
}
