<?php
/**
 * Created by PhpStorm.
 * User: evgeny
 * Date: 24.11.17
 * Time: 14:05
 */

namespace StoreBundle\Admin\Store\Payment\Method;


use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;

class AlfaBankTaxonAdmin extends AbstractAdmin
{

  public function configureListFields(ListMapper $list)
  {
    parent::configureListFields($list); // TODO: Change the autogenerated stub

    $list
      ->add('name')
      ->add('description')
      ->add('_action', null, array(
        'actions' => array(
          'edit' => [],
          'delete' => [],
        )
      ));
  }

  public function configureFormFields(FormMapper $form)
  {
    parent::configureFormFields($form); // TODO: Change the autogenerated stub

    $form
      ->add('name')
      ->add('description')
      ;
  }

}