<?php

namespace StoreBundle\Repository\Common;

/**
 * HomeBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeBannerRepository extends \Doctrine\ORM\EntityRepository
{
}
