<?php
/**
 * @author Denis N. Ragozin <dragozin@accurateweb.ru>
 */

namespace Accurateweb\FilteringBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PriceRangeFilterType extends AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $minWidgetOptions = array(
      'attr' => array(
        'class' => 'slider-min-value',
        'placeholder' => $options['range']['min'],
        'size' => 4
      )
    );

    $maxWidgetOptions = array(
      'attr' => array(
        'class' => 'slider-max-value',
        'placeholder' => $options['range']['max'],
        'size' => 4
      )
    );

    $builder
      ->add('min', TextType::class, $minWidgetOptions)
      ->add('max', TextType::class, $maxWidgetOptions);
  }

  public function buildView(FormView $view, FormInterface $form, array $options)
  {
    parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
  }

  public function getBlockPrefix()
  {
    return 'filter_range_slider';
  }

  public function configureOptions(OptionsResolver $resolver)
  {
    $resolver->setDefault('range', array(0, 0));
  }
}