<?php

namespace StoreBundle\Repository\Text;

/**
 * CustomerQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
