<?php

namespace StoreBundle\Repository\Text;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
  public function findRecent ($limit = 3)
  {
    return $this->_em->createQuery('SELECT n 
                                          FROM StoreBundle:Text\News n 
                                            WHERE n.published > 0
                                          ORDER BY 
                                            n.publishedAt DESC, 
                                            n.createdAt DESC')
      ->setMaxResults($limit)
      ->getResult();
  }
}
