<?php

namespace StoreBundle\Repository\Notification;
use Doctrine\ORM\EntityRepository;
use StoreBundle\Entity\User\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
  public function countNewNotificationsByUser(User $user)
  {
    return $this
      ->getNotificationsByUserQueryBuilder($user)
      ->select('COUNT(n) as nbNotifications')
      ->andWhere('n.read = false')
      ->getQuery()
      ->setMaxResults(1)
      ->getSingleScalarResult();
  }

  public function findNotificationsByUser(User $user)
  {
    return $this->getNotificationsByUserQueryBuilder($user)
      ->getQuery()
      ->getResult();
  }

  public function getNotificationsByUserQueryBuilder(User $user)
  {
    return $this->createQueryBuilder('n')
      ->where('n.user = :user')
      ->setParameter('user', $user)
      ->orderBy('n.read', 'ASC')
      ->addOrderBy('n.createdAt', 'DESC');
  }
}
